# config/routes.yaml

# Define tus rutas personalizadas aquí
ipsscan:
    path: /ipsscan
    controller: App\Controller\IPScanController::scanIPs

admin_ips_list:
    path: /ips
    controller: App\Controller\IpController::list

# Ruta para actualizar las IPs (GET)
actualizar_ips:
    path: /actualizar-ips
    controller: App\Controller\IpController::actualizarIps
    methods: ['GET']
